# Generated by Django 6.0.5 on 2026-05-31 19:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
